#! /bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
[ -x "$f" ] && . "$f"
done
unset f
fi

# Start compositor
picom -CG &

# xsetroot -cursor_name left_ptr solves problem with "cross" cursor
xsetroot -cursor_name left_ptr &

# # set background
hsetroot -solid "#000000" &

# # Hide cursor after 1 second of inactivity
unclutter --timeout 1 --ignore-scrolling &

# # Notifications daemon
dunst &

# tmux
# [ -f $HOME/.local/scripts/tmux_init ] &&
#     $HOME/.local/scripts/tmux_init &

# Volume bar
[ -p "$HOME"/.local/bin/xob_volume_fifo ] &&
  ( tail -f "$HOME"/.local/bin/xob_volume_fifo |
  xob -s volume >/dev/null 2>&1 & )

# Hot-key daemon
sxhkd -m -1 &

# Keyboard layout
test -f $HOME/.local/share/X11/xkb/qwerty.xkb &&
  xkbcomp $HOME/.local/share/X11/xkb/qwerty.xkb $DISPLAY &

# Window manager
exec bspwm
